# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HouseProducts' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # ignore all warnings from all pods
  inhibit_all_warnings!

  # Pods for HouseProducts

    pod 'Alamofire', '~> 4.7'
    pod 'Kingfisher', '~> 4.0'
    pod 'JGProgressHUD'
  target 'HouseProductsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HouseProductsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
